//
//  TermsAndConditions.swift
//  Dishly
//
//  Created by Vladimir Kovalev on 09.07.2023.
//

import Foundation

let termsAndConditions = """
Terms & Conditions
This is an agreement between you and VPN Proxy Master for virtual private network communications services, related services and features. It is NOT a service for the commission of criminal acts. It is an anonymity and privacy service. You agree not to violate any laws of any jurisdiction you are originating from, or terminating into.
You agree to protect your user id/password and our system from unauthorized use. You are responsible for all actions that occur on our servers where the login uses your user id/password.
You agree not to use the system for sending spam, port scanning, scanning for open proxies or open relays, sending opt-in email, unsolicited email or any type or version of email sent in large quantities even if the email is ultimately sent off of another server. You agree not to launch any pop-ups from our service. You agree not to attack in any way shape or form any other computer or network while on our service.
Actual service coverage, speeds, locations and quality may vary. The Service will attempt to be available at all times except for limited periods for maintenance and repair. However the Service may be subject to unavailability for a variety of factors beyond our control including emergencies, third party service failures, transmission, equipment or network problems or limitations, interference, signal strength, and may be interrupted, refused, limited or curtailed. We are not responsible for data, messages or pages lost, not delivered, delayed or misdirected because of interruptions or performance issues with the Service or communications services or networks (e.g., T-1 lines or the Internet). We may impose usage or Service limits, suspend Service, or block certain kinds of usage in our sole discretion to protect users or the Service. Network speed is an estimate and is no indication of the speed at which your or the Service sends or receives data. Actual network speed will vary based on configuration, compression, network congestion and other factors. The accuracy and timeliness of data received is not guaranteed; delays or omissions may occur.
We do not log any user activity (sites visited, DNS lookups, emails etc.) We only log access attempts to our servers (for security and troubleshooting). We do not get involved in any form of censorship. We do not give your personal info to any third parties. We do not cooperate with any requests for information unless we are ordered by a court of competent jurisdiction and the vast majority of these requests would not be from a court of competent jurisdiction We will protect you to the max and our system is setup to automatically do so. There are hundreds of good reasons for being anonymous and we respect them fully.
Hacking, cracking, distribution of viruses, fraudulent activities, network sabotage, phishing, and/or any conduct deemed illegal or unwanted shall be subject to suspension or termination. Users are responsible for the proper secure configuration of their services and are responsible for any damages caused by their neglect or exposure of vulnerabilities whether intentional or unintentional.
VPN Proxy Master does not put any cap on bandwidth or data usage per user however the use of service is subjected to fair usage. Creating automated or manual VPN sessions in a manner that would impersonate a bot or exerting excessive load on the network that may disturb other users on the network or utilizing substantially excessive bandwidth that exceeds the average user bandwidth usage for an extended duration or the likes, all are considered as unfair usage of the network. VPN Proxy Master reserves the right to temporary suspend or permanently terminate users found involved in unfair usage of its services.
"""
